[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jsxtractor"
version = "1.0.1"
description = "JavaScript extractor and regex scanner"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "rdzsp", email = "tool@rdzsp.id" }
]

license = { text = "MIT" }

keywords = [
  "javascript",
  "security",
  "regex",
  "playwright",
  "crawler",
  "bugbounty"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Security",
  "Topic :: Internet :: WWW/HTTP"
]

dependencies = [
  "random-user-agent==1.0.1",
  "requests==2.33.1",
  "PyYAML==6.0.3",
  "beautifulsoup4==4.14.3",
  "playwright==1.59.0"
]

[project.urls]
Homepage = "https://github.com/rdzsp/js-extractor-cli"
Repository = "https://github.com/rdzsp/js-extractor-cli"

[project.scripts]
jsxtractor = "jsxtractor.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]